
services:
  gravity_cms.field.choice:
    class: Gravity\CmsBundle\Field\Type\Choice\ChoiceField
    tags:
      - { name: gravity_cms.field }


  gravity_cms.field.choice.widget.select:
    class: Gravity\CmsBundle\Field\Type\Choice\Widget\Select\SelectWidget
    tags:
      - { name: gravity_cms.field.widget }


  # forms
  gravity_cms.field.choice.widget.select.form.json_choice:
    class: Gravity\CmsBundle\Field\Type\Choice\Widget\Select\JsonChoiceType
    tags:
      - { name: form.type, alias:json_choice }
