services:
  gravity_cms.search.adaptor.sql:
    class: Gravity\CmsBundle\Search\Adaptor\SqlSearchAdaptor
    arguments:
      - @doctrine.orm.default_entity_manager
      - @gravity_cms.field_manager

  gravity_cms.search.handler_manager:
    class: Gravity\CmsBundle\Search\Handler\HandlerManager

  gravity_cms.search.handler.node:
    class: Gravity\CmsBundle\Search\Handler\NodeHandler
    arguments:
      - @gravity_cms.search.adaptor.sql
      - @doctrine.orm.default_entity_manager
    tags:
      - { name: gravity_cms.search_handler }

  gravity_cms.search.handler.taxonomy:
    class: Gravity\CmsBundle\Search\Handler\TaxonomyHandler
    arguments:
      - @gravity_cms.search.adaptor.sql
      - @gravity_cms.field_manager
      - @doctrine.orm.default_entity_manager
    tags:
      - { name: gravity_cms.search_handler }
